apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenanta-operator-demo-role
  namespace: tenanta
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenanta-operator-demo-role-bindings
  namespace: tenanta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenanta-operator-demo-role
subjects:
- kind: ServiceAccount
  name: tenanta-operator-demo-sa
  namespace: tenanta
